using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace Agentic2D.Validation;

public sealed class VisualDefinitionValidator
{
    public const string VisualsScope = "visuals", Schema = "agentic2d.visual-definition.v1"; public static readonly string[] Layers = ["background", "ground", "entities", "foreground", "debug", "ui"];
    public VisualDefinitionValidationItem ValidateFile(string path) { var rel = ContentTargetResolver.ToRepositoryRelativePath(path); try { var d = JsonSerializer.Deserialize<VisualDefinitionSource>(File.ReadAllText(path), ContentValidationJson.Options); var errors = Validate(d!, rel); return new(d, rel, errors.Count == 0 ? ContentValidationStatus.Passed : ContentValidationStatus.Failed, errors); } catch (Exception e) when (e is IOException or JsonException) { return new(null, rel, ContentValidationStatus.Failed, [D(rel, "VISUAL0001", "json", e.Message)]); } }
    public IReadOnlyList<ContentValidationDiagnostic> Validate(VisualDefinitionSource d, string target) { var r = new List<ContentValidationDiagnostic>(); if (d is null || d.Schema != Schema || !Stable(d.Id) || !d.Id.StartsWith("visual-definition.")) r.Add(D(target, "VISUAL0001", "schema", "Invalid visual definition schema or ID.")); if (d?.Parts.Count == 0) r.Add(D(target, "VISUAL0001", "parts", "Visual definition needs parts.")); var ids = new HashSet<string>(); foreach (var p in d?.Parts ?? []) { if (!Stable(p.Id) || !ids.Add(p.Id)) r.Add(D(target, "VISUAL0002", "parts[].id", "Duplicate/invalid part ID.", p.Id)); if (!Stable(p.AssetId) || !Stable(p.RegionId)) r.Add(D(target, "VISUAL0003", "parts", "Asset and region IDs are required.", p.Id)); if (!new[] { "top-left", "center", "bottom-center" }.Contains(p.Anchor) || !Layers.Contains(p.Layer) || !new[] { "fixed", "y" }.Contains(p.SortMode)) r.Add(D(target, "VISUAL0004", "parts", "Unsupported anchor/layer/sort mode.", p.Id)); if (!double.IsFinite(p.Offset.X) || !double.IsFinite(p.Offset.Y) || !double.IsFinite(p.WorldSize.Width) || !double.IsFinite(p.WorldSize.Height) || p.WorldSize.Width <= 0 || p.WorldSize.Height <= 0) r.Add(D(target, "VISUAL0005", "parts", "Invalid finite world geometry.", p.Id)); } return r.OrderBy(x => x.Id, StringComparer.Ordinal).ThenBy(x => x.ItemId, StringComparer.Ordinal).ToArray(); }
    static bool Stable(string? x) => !string.IsNullOrWhiteSpace(x) && x.All(c => char.IsLetterOrDigit(c) || c is '.' or '-'); static ContentValidationDiagnostic D(string t, string id, string f, string m, string? i = null) => new(id, ContentDiagnosticSeverity.Error, m, t, f, i);
}
public sealed class VisualDefinitionCatalog
{
    public VisualDefinitionCatalog(IReadOnlyDictionary<string, VisualDefinitionSource> d, string r) { Definitions = d; Revision = r; }
    public IReadOnlyDictionary<string, VisualDefinitionSource> Definitions { get; }
    public string Revision { get; }
    public bool TryGet(string id, out VisualDefinitionSource? d) => Definitions.TryGetValue(id, out d);
    public static VisualDefinitionCatalog LoadAll(out IReadOnlyList<ContentValidationDiagnostic> diagnostics) { var root = Path.Combine(ContentTargetResolver.FindRepositoryRoot(), "game", "visuals"); var v = new VisualDefinitionValidator(); var a = new List<ContentValidationDiagnostic>(); var d = new Dictionary<string, VisualDefinitionSource>(); foreach (var p in Directory.Exists(root) ? Directory.EnumerateFiles(root, "*.json").Order().ToArray() : Array.Empty<string>()) { var x = v.ValidateFile(p); a.AddRange(x.Diagnostics); if (x.Definition is not null && x.Status == ContentValidationStatus.Passed && !d.TryAdd(x.Definition.Id, x.Definition)) a.Add(new("VISUAL0002", ContentDiagnosticSeverity.Error, "Duplicate visual ID.", x.Path, "id", x.Definition.Id)); } diagnostics = a; var raw = string.Join("|", d.OrderBy(x => x.Key).Select(x => x.Key + JsonSerializer.Serialize(x.Value))); return new(d, "sha256:" + Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(raw))).ToLowerInvariant()); }
}
public sealed record VisualDefinitionValidationItem(VisualDefinitionSource? Definition, string Path, string Status, IReadOnlyList<ContentValidationDiagnostic> Diagnostics);
public sealed class VisualDefinitionSource { [JsonPropertyName("schema")] public string Schema { get; init; } = ""; [JsonPropertyName("id")] public string Id { get; init; } = ""; [JsonPropertyName("parts")] public IReadOnlyList<VisualPartSource> Parts { get; init; } = []; }
public sealed record VisualPartSource([property: JsonPropertyName("id")] string Id, [property: JsonPropertyName("assetId")] string AssetId, [property: JsonPropertyName("regionId")] string RegionId, [property: JsonPropertyName("anchor")] string Anchor, [property: JsonPropertyName("offset")] VisualPoint Offset, [property: JsonPropertyName("worldSize")] VisualSize WorldSize, [property: JsonPropertyName("layer")] string Layer, [property: JsonPropertyName("order")] int Order, [property: JsonPropertyName("sortMode")] string SortMode, [property: JsonPropertyName("tint")] VisualColor Tint);
public sealed record VisualPoint([property: JsonPropertyName("x")] double X, [property: JsonPropertyName("y")] double Y); public sealed record VisualSize([property: JsonPropertyName("width")] double Width, [property: JsonPropertyName("height")] double Height); public sealed record VisualColor([property: JsonPropertyName("r")] int R, [property: JsonPropertyName("g")] int G, [property: JsonPropertyName("b")] int B, [property: JsonPropertyName("a")] int A);
