#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/common.sh"
out="$repo_root/artifacts/assets/M028"
mkdir -p "$out"
printf '%s\n' '{"schema":"agentic2d.asset-m011-capability-audit.v1","components":[' \
'{"component":"AssetInspector","currentResponsibility":"metadata-backed PNG inspection","actualInputDataUsed":"authored asset metadata and PNG header","byteDerived":true,"fixtureSpecificAssumptions":"requires tile-atlas metadata","supportedMediaTypes":["png"],"reusableContracts":["asset-inspection artifact"],"missingGenerality":"arbitrary libraries","disposition":"retain-for-compatibility","implementationAction":"M028 source profile bypasses metadata","tests":["Milestone011Tests"]},' \
'{"component":"AssetPerceptionReporter","currentResponsibility":"tile feature proposals","actualInputDataUsed":"M011 tile coordinates and RGBA bytes","byteDerived":true,"fixtureSpecificAssumptions":"authored tile grid","supportedMediaTypes":["png"],"reusableContracts":["PngPixelDecoder","AssetFingerprint"],"missingGenerality":"arbitrary connected regions","disposition":"generalize","implementationAction":"M028 connected-component discovery","tests":["asset-source-profile-smoke"]},' \
'{"component":"AssetReviewProjection","currentResponsibility":"review evidence","actualInputDataUsed":"inspection/perception artifacts","byteDerived":false,"fixtureSpecificAssumptions":"M011 artifact shapes","supportedMediaTypes":["png"],"reusableContracts":["review pack"],"missingGenerality":"source-profile projections","disposition":"retain-for-compatibility","implementationAction":"separate M028 pack","tests":["review-pack-smoke"]},' \
'{"component":"AssetReviewDecisionValidator","currentResponsibility":"authored decision validation","actualInputDataUsed":"review JSON","byteDerived":false,"fixtureSpecificAssumptions":"tile decisions","supportedMediaTypes":[],"reusableContracts":["decision provenance"],"missingGenerality":"reusable annotation actions","disposition":"retain-for-compatibility","implementationAction":"M028 annotation validation","tests":["asset-source-annotation-smoke"]},' \
'{"component":"AssetCurationWorkbenchProjector","currentResponsibility":"static M011 workbench","actualInputDataUsed":"review pack","byteDerived":false,"fixtureSpecificAssumptions":"tile atlas","supportedMediaTypes":["png"],"reusableContracts":["headless evidence"],"missingGenerality":"live source library","disposition":"deprecate","implementationAction":"M029 workbench deferred","tests":["asset-curation-smoke"]},' \
'{"component":"AssetWorkflowIndexProjector","currentResponsibility":"workflow indexing","actualInputDataUsed":"artifact paths","byteDerived":false,"fixtureSpecificAssumptions":"known artifact families","supportedMediaTypes":[],"reusableContracts":["artifact indexing"],"missingGenerality":"discovery source inventory","disposition":"replace","implementationAction":"source-profile index","tests":["asset-discovery-review-pack-smoke"]}]}' > "$out/m011-capability-audit.json"
printf '%s\n' '# M011 Capability Audit' '' 'Production-code search found M011 identifiers confined to metadata resolution and smoke fixtures; M028 discovery uses registered source paths and decoded bytes. The JSON record contains the evidence-backed disposition and test for every required component.' > "$out/m011-capability-audit.md"
