using Agentic2D.Simulation;

namespace Agentic2D.Tests.Unit;

public sealed class M032AutonomousDetailedRegionTests
{
    [Test] public async Task AutonomousWorkCompletesTheBoundedLoop() => await Assert.That(M032AutonomousDetailedRegion.Direct().Diagnostics).IsEmpty();
    [Test] public async Task WorkOpportunityDerivationIsStableAndReadOnly() { var world = M032AutonomousDetailedRegion.CreateInitial(); var before = world.Fingerprint(); var opportunities = M032AutonomousDetailedRegion.DeriveOpportunities(world, [new("designation.extraction.001", "resource-extraction", "region.forest.active", [], 10, true, 2), new("designation.storage.001", "storage", "region.forest.active", [], 5, true, 1)]); await Assert.That(opportunities.Select(x => x.Key)).IsEquivalentTo(opportunities.Select(x => x.Key).Order(StringComparer.Ordinal)); await Assert.That(world.Fingerprint()).IsEqualTo(before); }
    [Test] public async Task WorkerSelectionIsDeterministicAndExplained() { var run = M032AutonomousDetailedRegion.Direct(); await Assert.That(run.Decisions.First(x => x.WorkerId == "worker.002").Rejections).Contains("harvest:tree.001:reservation-unavailable"); }
    [Test] public async Task WorkerAssignmentAtomicallyRejectsAContendedTarget() { var world = M032AutonomousDetailedRegion.CreateInitial(); var first = world.CreateActivityWithReservations(new("activity.assignment.one"), "worker.001", "harvest", "planned", ["tree.001"], [new(new("reservation.assignment.one"), "tree.001", "exclusive.harvest", 1, 1)], new("test"), new("test")); var second = world.CreateActivityWithReservations(new("activity.assignment.two"), "worker.002", "harvest", "planned", ["tree.001"], [new(new("reservation.assignment.two"), "tree.001", "exclusive.harvest", 1, 1)], new("test"), new("test")); await Assert.That(first.Status).IsEqualTo("accepted"); await Assert.That(second.Status).IsEqualTo("rejected"); await Assert.That(world.Activities.Select(x => x.Id)).DoesNotContain("activity.assignment.two"); }
    [Test] public async Task DetailedGridNavigationHasStableFourDirectionalPaths() { var route = M032AutonomousDetailedRegion.FindRoute("test", "worker", new(0, 0), new(2, 2)); var replanned = M032AutonomousDetailedRegion.FindRoute("test.replan", "worker", new(0, 0), new(2, 2), new HashSet<DetailedCell> { new(1, 0) }); await Assert.That(route.Status).IsEqualTo("found"); await Assert.That(route.Path.Count).IsEqualTo(4); await Assert.That(replanned.Status).IsEqualTo("found"); await Assert.That(replanned.Fingerprint).IsNotEqualTo(route.Fingerprint); }
    [Test] public async Task DetailedActivityExecutionUsesCommandsAndCompletes() { var run = M032AutonomousDetailedRegion.Direct(); await Assert.That(run.World.Activities.Where(x => x.Kind == "harvest-and-haul").All(x => x.Status == SimulationActivityStatus.Completed)).IsTrue(); }
    [Test] public async Task LogisticsConservesWoodAndReleasesReservations() { var run = M032AutonomousDetailedRegion.Direct(); await Assert.That(run.World.Reservations.All(x => x.Status != SimulationReservationStatus.Active)).IsTrue(); await Assert.That(run.Diagnostics).IsEmpty(); }
    [Test] public async Task BasicNeedsInterruptAtSemanticBoundary() { var run = M032AutonomousDetailedRegion.Direct(); await Assert.That(run.World.Activities.Single(x => x.Id == "activity.need.food.001").Status).IsEqualTo(SimulationActivityStatus.Completed); await Assert.That(run.Decisions.Single(x => x.SelectedOpportunityKey == "eat:worker.001").Interruption).IsEqualTo("mandatory-food"); await Assert.That(run.World.Events.Select(x => x.Type)).Contains("NeedIntegrated"); }
    [Test] public async Task DetailedRegionPersistenceReconstructsAndMatchesFingerprint() { var direct = M032AutonomousDetailedRegion.Direct(); var roundtrip = M032AutonomousDetailedRegion.RoundTrip(out _); await Assert.That(roundtrip.Fingerprint).IsEqualTo(direct.Fingerprint); await Assert.That(roundtrip.RouteEvents).Contains("reconstructed-after-load:activity.harvest.001"); }
    [Test] public async Task DetailedRegionProjectionHasBoundedStructuralEvidence() { var run = M032AutonomousDetailedRegion.Direct(); await Assert.That(run.Navigation.Count).IsGreaterThan(0); await Assert.That(run.RouteEvents).Contains("replanned:activity.harvest.001"); }
    [Test] public async Task DesignationCommandsCreateEditAndRemovePersistentEntities() { var world = M032AutonomousDetailedRegion.CreateInitial(); var designation = new WorkDesignation("designation.player.test.001", "resource-extraction", "region.forest.active", [new(5, 3)], 4, true, 1); await Assert.That(M032AutonomousDetailedRegion.CreateDesignation(world, designation).Status).IsEqualTo("accepted"); await Assert.That(M032AutonomousDetailedRegion.SetDesignationPriority(world, designation.Id, 9).Status).IsEqualTo("accepted"); await Assert.That(M032AutonomousDetailedRegion.SetDesignationEnabled(world, designation.Id, false).Status).IsEqualTo("accepted"); var edited = M032AutonomousDetailedRegion.InspectDesignations(world).Single(x => x.Id == designation.Id); await Assert.That(edited.Priority).IsEqualTo(9); await Assert.That(edited.Enabled).IsFalse(); await Assert.That(edited.Revision).IsEqualTo(3); await Assert.That(M032AutonomousDetailedRegion.CreateDesignation(world, designation).Status).IsEqualTo("rejected"); await Assert.That(M032AutonomousDetailedRegion.RemoveDesignation(world, designation.Id).Status).IsEqualTo("accepted"); await Assert.That(M032AutonomousDetailedRegion.InspectDesignations(world).Select(x => x.Id)).DoesNotContain(designation.Id); }
    [Test] public async Task DerivationTracksDesignationEnablementRemovalAndAllNeedFamilies() { var world = M032AutonomousDetailedRegion.CreateInitial(); await Assert.That(M032AutonomousDetailedRegion.SetDesignationEnabled(world, "designation.extraction.001", false).Status).IsEqualTo("accepted"); var disabled = M032AutonomousDetailedRegion.DeriveOpportunities(world, M032AutonomousDetailedRegion.InspectDesignations(world)); await Assert.That(disabled.Single(x => x.Key == "harvest:tree.001").BlockingReason).IsEqualTo("designation-disabled"); await Assert.That(M032AutonomousDetailedRegion.RemoveDesignation(world, "designation.extraction.001").Status).IsEqualTo("accepted"); var removed = M032AutonomousDetailedRegion.DeriveOpportunities(world, M032AutonomousDetailedRegion.InspectDesignations(world)); await Assert.That(removed.Single(x => x.Key == "harvest:tree.001").BlockingReason).IsEqualTo("target-not-designated"); await Assert.That(removed.Select(x => x.Family)).Contains("eat"); await Assert.That(removed.Select(x => x.Family)).Contains("drink"); await Assert.That(removed.Select(x => x.Family)).Contains("rest"); }
    [Test] public async Task SelectionIsReadOnlyAndReportsContendedReservation() { var world = M032AutonomousDetailedRegion.CreateInitial(); var before = world.Fingerprint(); var first = M032AutonomousDetailedRegion.EvaluateWorker(world, "worker.001", M032AutonomousDetailedRegion.DeriveOpportunities(world, M032AutonomousDetailedRegion.InspectDesignations(world))); await Assert.That(first.SelectedOpportunityKey).IsEqualTo("harvest:tree.001"); await Assert.That(world.Fingerprint()).IsEqualTo(before); await Assert.That(world.CreateActivityWithReservations(new("activity.selection.test"), "worker.001", "harvest", "planned", ["tree.001"], [new(new("reservation.selection.test"), "tree.001", "exclusive.harvest", 1, 1)], new("test"), new("test")).Status).IsEqualTo("accepted"); var second = M032AutonomousDetailedRegion.EvaluateWorker(world, "worker.002", M032AutonomousDetailedRegion.DeriveOpportunities(world, M032AutonomousDetailedRegion.InspectDesignations(world))); await Assert.That(second.Rejections).Contains("harvest:tree.001:reservation-unavailable"); await Assert.That(second.SelectedOpportunityKey).IsEqualTo("harvest:tree.002"); }
    [Test] public async Task EvidenceStatesAreDistinctAuthoritativeSnapshots() { var states = M032AutonomousDetailedRegion.CreateEvidenceStates(); await Assert.That(states.Keys).IsEquivalentTo(["initial", "movement", "interruption", "post-load"]); await Assert.That(states["initial"].Fingerprint).IsNotEqualTo(states["movement"].Fingerprint); await Assert.That(states["movement"].Fingerprint).IsNotEqualTo(states["interruption"].Fingerprint); await Assert.That(states["interruption"].World.Activities.Single().Status).IsEqualTo(SimulationActivityStatus.Interrupted); await Assert.That(states["post-load"].RouteEvents).Contains("reconstructed-after-load:activity.harvest.001"); }
}
