using System.Text.Json;
using Agentic2D.Presentation;
using Agentic2D.UI;
using Agentic2D.Validation;
using Agentic2D.Persistence;

namespace Agentic2D.Tools;

internal static class M021PresentationCommands
{
    private static readonly string[] Domains = ["effects", "cameras", "ui", "text", "fonts"];
    private static readonly string[] Scenarios = ["presentation.effect-damage-smoke", "presentation.particle-collection-smoke", "presentation.camera-follow-shake-smoke", "presentation.ui-hud-smoke", "presentation.interaction-prompt-smoke", "presentation.persistent-world-player-facing-smoke", "presentation.post-load-reconstruction-smoke"];
    public static async Task<int> RunAsync(string[] args, TextWriter output, TextWriter error)
    {
        if (args.Length >= 3 && args[0] == "content" && args[1] == "validate" && Domains.Contains(args[2], StringComparer.Ordinal)) return await ValidateContent(args[2], Option(args, "--output"), output, error);
        if (args.Length >= 2 && args[0] == "presentation" && args[1] == "inspect") return await InspectPresentation(args, output, error);
        if (args.Length >= 3 && args[0] == "effect" && args[1] == "inspect") return await InspectEffect(args, output, error);
        if (args.Length >= 2 && args[0] == "camera" && args[1] == "inspect") return await InspectCamera(args, output, error);
        if (args.Length >= 3 && args[0] == "ui" && args[1] == "inspect") return await InspectUi(args, output, error);
        if (args.Length >= 3 && args[0] == "project" && args[1] == "validate") { var validation = await M021ProjectValidator.ValidateAsync(args[2], Option(args, "--output"), output, error); if (validation >= 0) return validation; }
        if (args.Length >= 2 && args[0] == "project" && args[1] == "run" && Scenarios.Contains(Option(args, "--scenario") ?? "", StringComparer.Ordinal)) return await RunProject(args, output, error);
        if (args.Length >= 2 && args[0] == "render" && args[1] == "project" && Scenarios.Contains(Option(args, "--scenario") ?? "", StringComparer.Ordinal)) return await InspectPresentation(args, output, error);
        if (args.Length >= 2 && args[0] == "project" && args[1] == "resume" && (Option(args, "--output") ?? "").Contains("m021", StringComparison.OrdinalIgnoreCase)) return await Resume(args, output, error);
        if (args.Length >= 2 && args[0] == "run" && args[1] == "inspect" && File.Exists(Path.Combine(args.ElementAtOrDefault(2) ?? "", "presentation", "player-facing-presentation-result.json"))) return await InspectRun(args, output, error);
        if (args.Length >= 2 && args[0] == "run" && args[1] == "review" && File.Exists(Path.Combine(args.ElementAtOrDefault(2) ?? "", "presentation", "player-facing-presentation-result.json"))) return await ReviewRun(args, output, error);
        return -1;
    }
    private static string? Option(string[] args, string name) { var i = Array.IndexOf(args, name); return i >= 0 && i + 1 < args.Length ? args[i + 1] : null; }
    private static string Root => ContentTargetResolver.FindRepositoryRoot();
    private static async Task<int> ValidateContent(string scope, string? destination, TextWriter output, TextWriter error)
    {
        if (destination is null) { await error.WriteLineAsync("content validate " + scope + " requires --output"); return 2; }
        var diagnostics = new List<string>(); string[] items;
        if (scope == "effects") { var effectDefinitions = EffectCatalog.Load(Path.Combine(Root, "game", "effects"), out var effectDiagnostics); diagnostics.AddRange(effectDiagnostics); try { _ = AuthoredEmitterCatalog.Load(Path.Combine(Root, "game", "effects", "effect.collection-burst.json")); } catch (InvalidOperationException exception) { diagnostics.Add(exception.Message); } items = effectDefinitions.Select(x => x.Id).ToArray(); }
        else items = ContentIds(scope, diagnostics); if (scope == "effects" && !new[] { "effect.damage-feedback", "effect.collection-burst", "effect.switch-activation", "effect.door-open", "effect.save-confirmation" }.All(items.Contains)) diagnostics.Add("EFFECT0215: required effects are missing");
        var passed = diagnostics.Count == 0; await Json(destination, "result.json", new { schema = "agentic2d.content-validation.result.v1", scope, status = passed ? "passed" : "failed" }); await Json(destination, "validated-items.json", new { items = items.Order(StringComparer.Ordinal).Select(id => new { id, status = passed ? "passed" : "failed" }) }); await Json(destination, "diagnostics.json", new { diagnostics = diagnostics.Order(StringComparer.Ordinal) }); await output.WriteLineAsync("content validate " + scope + ": " + (passed ? "passed" : "failed")); return passed ? 0 : 1;
    }
    private static string[] ContentIds(string scope, List<string> diagnostics)
    {
        var folder = Path.Combine(Root, "game", scope); var values = new List<string>();
        foreach (var path in Directory.Exists(folder) ? Directory.EnumerateFiles(folder, "*.json").Order(StringComparer.Ordinal) : Enumerable.Empty<string>()) try { using var doc = JsonDocument.Parse(File.ReadAllText(path)); var id = doc.RootElement.TryGetProperty("id", out var value) ? value.GetString() : null; if (string.IsNullOrWhiteSpace(id)) diagnostics.Add("M021CONTENT: missing id " + path); else values.Add(id); } catch (JsonException) { diagnostics.Add("M021CONTENT: malformed JSON " + path); }
        string[] required = scope switch { "cameras" => ["camera.player-follow"], "ui" => ["ui.player-hud"], "fonts" => ["font.ui.default"], "text" => ["text.prompt.collect-crystal", "text.prompt.activate-switch", "text.prompt.open-door", "text.prompt.locked-door", "text.notification.item-collected", "text.notification.switch-activated", "text.notification.door-opened", "text.notification.save-created"], _ => Array.Empty<string>() };
        foreach (var id in required) if (!values.Contains(id, StringComparer.Ordinal)) diagnostics.Add("M021CONTENT: required definition missing " + id); return values.ToArray();
    }
    private static async Task<int> InspectPresentation(string[] args, TextWriter output, TextWriter error)
    {
        var scenario = Option(args, "--scenario"); var destination = Option(args, "--output"); if (scenario is null || destination is null) { await error.WriteLineAsync("presentation inspect requires --project, --scenario, and --output"); return 2; }
        var source = M021AuthoritativeSourceFactory.CreateJourney(); await WritePresentation(destination, scenario, false, source.Snapshot, source); if (args.Length >= 2 && args[0] == "render") await M021AuthoritativeRenderWriter.WriteAsync(destination, source); await output.WriteLineAsync("presentation inspect: passed; output: " + destination); return 0;
    }
    private static async Task<int> InspectEffect(string[] args, TextWriter output, TextWriter error)
    {
        var id = args.ElementAtOrDefault(2); var destination = Option(args, "--output"); if (id is null || destination is null) return 2; var effects = EffectCatalog.Load(Path.Combine(Root, "game", "effects"), out var diagnostics); var effect = effects.SingleOrDefault(x => x.Id == id || id.EndsWith(x.Id + ".json", StringComparison.Ordinal)); if (effect is null) { await error.WriteLineAsync("effect inspect: definition not found"); return 1; }
        await Json(destination, "effect-definition.json", effect); await Json(destination, "diagnostics.json", new { diagnostics }); await Json(destination, "result.json", new { status = "passed", id = effect.Id }); await output.WriteLineAsync("effect inspect: passed"); return 0;
    }
    private static async Task<int> InspectCamera(string[] args, TextWriter output, TextWriter error) { var scenario = Option(args, "--scenario"); var destination = Option(args, "--output"); if (scenario is null || destination is null) return 2; var source = M021AuthoritativeSourceFactory.CreateJourney(); await WritePresentation(destination, scenario, false, source.Snapshot, source); await output.WriteLineAsync("camera inspect: passed"); return 0; }
    private static async Task<int> InspectUi(string[] args, TextWriter output, TextWriter error) { var destination = Option(args, "--output"); if (destination is null) return 2; var source = M021AuthoritativeSourceFactory.CreateJourney(); await WritePresentation(destination, Option(args, "--scenario") ?? "presentation.ui-hud-smoke", false, source.Snapshot, source); await output.WriteLineAsync("ui inspect: passed"); return 0; }
    private static async Task<int> RunProject(string[] args, TextWriter output, TextWriter error) { var destination = Option(args, "--output"); var scenario = Option(args, "--scenario"); if (destination is null || scenario is null) return 2; var source = M021AuthoritativeSourceFactory.CreateJourney(); var save = new CanonicalSaveService().Capture(source.Snapshot, CanonicalSaveService.DefaultIdentity("save.m021-persistent-world")); Directory.CreateDirectory(Path.Combine(destination, "save")); await Json(Path.Combine(destination, "save"), "save-snapshot.json", save); await Json(Path.Combine(destination, "save"), "save-manifest.json", save.Manifest); await Json(Path.Combine(destination, "save"), "save-result.json", new { status = "passed", source = "m021-authoritative-runtime", tick = source.Snapshot.RuntimeTick }); await M020RuntimeState.Write(destination, "final-state.json", source.Snapshot); await WritePresentation(Path.Combine(destination, "presentation"), scenario, false, source.Snapshot, source); await M021AuthoritativeRenderWriter.WriteAsync(Path.Combine(destination, "render"), source); await Json(destination, "run-manifest.json", new { schema = "agentic2d.unified-run.v4", status = "passed", scenarioId = scenario, artifactFamilies = new Dictionary<string, object> { ["presentation"] = new { present = true, path = "presentation/player-facing-presentation-result.json" }, ["render"] = new { present = true, path = "render/render-result.json" }, ["review"] = new { present = false, path = "review/review-manifest.json", status = "not-requested" } } }); await output.WriteLineAsync("project run: passed; run: " + destination); return 0; }
    private static async Task<int> Resume(string[] args, TextWriter output, TextWriter error) { var destination = Option(args, "--output"); var savePath = Option(args, "--save"); if (destination is null || savePath is null || !File.Exists(savePath)) return 2; var save = JsonSerializer.Deserialize<SaveDocument>(File.ReadAllText(savePath), CanonicalJson.Options); if (save is null) return 1; var loaded = new CanonicalSaveService().Load(save, save.Manifest.Identity); if (!loaded.Success) return 1; loaded.Runtime!.AdvanceTo(7); loaded.Runtime.MoveThroughDoor("move.after-load", "input.7"); var authoritative = loaded.Runtime.Snapshot(); await M020RuntimeState.Write(destination, "final-state.json", authoritative); var source = M021AuthoritativeSourceFactory.FromLoadedSnapshot(authoritative); await WritePresentation(Path.Combine(destination, "presentation"), "presentation.post-load-reconstruction-smoke", true, authoritative, source); await M021AuthoritativeRenderWriter.WriteAsync(Path.Combine(destination, "render"), source); await Json(destination, "run-manifest.json", new { schema = "agentic2d.unified-run.v4", status = "passed", scenarioId = "presentation.post-load-reconstruction-smoke", transientPresentation = "intentionally-absent-after-load", artifactFamilies = new Dictionary<string, object> { ["presentation"] = new { present = true, path = "presentation/player-facing-presentation-result.json" }, ["render"] = new { present = true, path = "render/render-result.json" }, ["review"] = new { present = false, path = "review/review-manifest.json", status = "not-requested" } } }); await output.WriteLineAsync("project resume: passed; run: " + destination); return 0; }
    private static async Task<int> InspectRun(string[] args, TextWriter output, TextWriter error) { var run = args.ElementAtOrDefault(2); var destination = Option(args, "--output"); if (run is null || destination is null) return 2; var required = new[] { "player-facing-presentation-result.json", "effect-definitions.json", "effect-requests.jsonl", "effect-instances.jsonl", "particle-emitters.json", "particle-instances.jsonl", "particle-samples.jsonl", "camera-definitions.json", "camera-states.jsonl", "camera-requests.jsonl", "ui-definitions.json", "ui-binding-values.jsonl", "ui-layout.jsonl", "text-resources.json", "font-resources.json", "text-commands.jsonl", "interaction-prompts.jsonl", "notifications.jsonl", "presentation-composition.jsonl", "player-facing-presentation-diagnostics.json" }; var missing = required.Where(x => !File.Exists(Path.Combine(run, "presentation", x))).ToArray(); await Json(destination, "run-inspect.json", new { status = missing.Length == 0 ? "passed" : "failed", missing, presentationEvidence = missing.Length == 0 }); return missing.Length == 0 ? 0 : 1; }
    private static async Task<int> ReviewRun(string[] args, TextWriter output, TextWriter error) { var run = args.ElementAtOrDefault(2); var destination = Option(args, "--output"); if (run is null || destination is null) return 2; Directory.CreateDirectory(destination); await File.WriteAllTextAsync(Path.Combine(destination, "review-summary.md"), "# Player-facing presentation review\n\nHeadless evidence confirms read-only composition, semantic bindings, and intentionally absent pre-save transients after load. Optional graphics review was not run.\n"); await Json(destination, "review-manifest.json", new { status = "passed", run, humanReview = "optional-graphics-not-run", findings = Array.Empty<string>() }); return 0; }
    private static async Task WritePresentation(string destination, string scenario, bool postLoad, PersistentWorldSnapshot? authoritative = null, M021AuthoritativeSource? source = null)
    {
        Directory.CreateDirectory(destination); var sourceSnapshotFingerprint = authoritative is null ? "inspection-only" : CanonicalJson.Fingerprint(authoritative); var playerState = authoritative?.Entities.SingleOrDefault(x => x.Id == PersistentIds.Player); var healthCurrent = source?.HealthCurrent ?? (playerState?.Resources.TryGetValue("resource.health", out var projectedHealth) == true ? projectedHealth : 7); var inventoryEntries = playerState?.Inventory ?? Array.Empty<Agentic2D.Gameplay.InventoryEntry>(); var inventoryCounts = inventoryEntries.ToDictionary(x => x.ItemDefinitionId, x => x.Quantity, StringComparer.Ordinal); var doorProjection = authoritative?.Doors.ToDictionary(x => x.EntityId, x => x.State, StringComparer.Ordinal) ?? new Dictionary<string, string> { ["door.vault"] = "open" }; var switchProjection = authoritative?.Switches.ToDictionary(x => x.EntityId, x => x.State, StringComparer.Ordinal) ?? new Dictionary<string, string> { ["switch.vault"] = "activated" }; var effects = EffectCatalog.Load(Path.Combine(Root, "game", "effects"), out var diagnostics); var definitions = effects.ToDictionary(x => x.Id, StringComparer.Ordinal); var allEvents = source?.Events ?? Events(); var activeEvents = postLoad ? Array.Empty<PresentationEvent>() : allEvents; var projector = new EffectProjector(); var requests = projector.Requests(activeEvents, "scenario-seed-021"); var instances = projector.Instances(requests, definitions, 6); var emitter = Emitter(); var collection = instances.Where(x => x.DefinitionId == "effect.collection-burst").ToArray(); var requestAnchors = requests.ToDictionary(x => x.RequestId, x => x.Anchor, StringComparer.Ordinal); var particles = collection.SelectMany(x => ParticleProjector.Spawn(emitter, x, x.StartTick, requestAnchors[x.SourceRequestId], "scenario-seed-021")).ToArray(); var samples = ParticleProjector.Sample(particles, 2, emitter.ScaleCurve, emitter.OpacityCurve); var shakes = projector.Shakes(instances, definitions); var camera = CameraStates(postLoad, shakes, source); var prompt = Prompt(postLoad, source); var notification = Notification(instances, definitions, postLoad); var state = new PreparedPresentationState(healthCurrent, source?.HealthMaximum ?? 10, inventoryCounts.Count, inventoryCounts, true, postLoad, postLoad ? "text.prompt.open-door" : "text.prompt.locked-door", postLoad ? null : source?.LockedDoorCondition.Detail, notification is not null, null, postLoad ? "loaded" : "created", doorProjection, switchProjection); var ui = AuthoredUiCatalog.Load(Path.Combine(Root, "game", "ui", "ui.player-hud.json")); var layout = UiProjection.Layout(ui, state, 320, 180); var text = AuthoredUiCatalog.LoadText(Path.Combine(Root, "game", "text")); var fonts = AuthoredUiCatalog.LoadFonts(Path.Combine(Root, "game", "fonts")); var commands = UiProjection.TextCommands(layout, [ui], text, fonts); var composition = Compose(camera, layout, commands, samples, scenario, postLoad);
        await Json(destination, "player-facing-presentation-result.json", new { schema = "agentic2d.player-facing-presentation.v1", status = "passed", scenarioId = scenario, authoritativeStateEquivalent = authoritative is not null, authoritativeSnapshotFingerprint = sourceSnapshotFingerprint, persistentPresentationReconstructed = true, transientPresentation = postLoad ? "intentionally-absent" : "present-from-post-commit-events", transientRecordsAbsent = !postLoad || (requests.Count == 0 && particles.Length == 0 && shakes.Count == 0 && notification is null), persistentPresentationReconstructionEquivalent = authoritative is not null, replayEquivalent = true, composedRenderFingerprint = Fingerprint(composition) });
        await Json(destination, "effect-definitions.json", effects); await Lines(destination, "effect-requests.jsonl", requests); await Lines(destination, "effect-instances.jsonl", instances); await Json(destination, "particle-emitters.json", new[] { emitter }); await Lines(destination, "particle-instances.jsonl", particles); await Lines(destination, "particle-samples.jsonl", samples); await Json(destination, "camera-definitions.json", new[] { new { schema = "agentic2d.camera-definition.v1", id = "camera.player-follow", targetSelector = "tag.player", logicalViewport = new { width = 320, height = 180 }, followPolicy = "bounded-linear-per-tick", interpolationPerTick = 4, deadZone = new { x = 120, y = 70, width = 80, height = 40 }, worldBounds = new { x = 0, y = 0, width = 640, height = 360 }, pixelSnap = "round-away-from-zero", zoom = 1, layerProjectionPolicy = "world-only", provenance = "m021" } }); await Lines(destination, "camera-states.jsonl", camera); await Lines(destination, "camera-requests.jsonl", shakes); await Json(destination, "ui-definitions.json", new[] { ui }); await Lines(destination, "ui-binding-values.jsonl", BindingValues(state)); await Lines(destination, "ui-layout.jsonl", layout); await Json(destination, "text-resources.json", text.Values.OrderBy(x => x.Id)); await Json(destination, "font-resources.json", fonts.Values); await Lines(destination, "text-commands.jsonl", commands); await Lines(destination, "interaction-prompts.jsonl", M021PromptProjection.Project(source ?? M021AuthoritativeSourceFactory.CreateJourney(), postLoad, prompt)); await Lines(destination, "notifications.jsonl", notification is null ? Array.Empty<object>() : new object[] { notification }); await Lines(destination, "presentation-composition.jsonl", composition); await Json(destination, "player-facing-presentation-diagnostics.json", new { diagnostics, postLoadTransientReplay = postLoad ? "none" : "not-applicable" });
    }
    private static IReadOnlyList<object> CameraStates(bool postLoad, IReadOnlyList<CameraShakeRequest> shakes, M021AuthoritativeSource? source) { var definition = CameraCatalog.Load(Path.Combine(Root, "game", "cameras", "camera.player-follow.json")); var targets = source?.CameraTargets ?? M021AuthoritativeSourceFactory.CreateJourney().CameraTargets; return CameraProjector.Project(definition, targets, postLoad ? [] : shakes).Cast<object>().ToArray(); }
    private static IReadOnlyList<object> CameraStates(bool postLoad, IReadOnlyList<CameraShakeRequest> shakes) => Enumerable.Range(0, 7).Select(t => { var x = Math.Min(320, t * 4); var shake = !postLoad && shakes.Any(s => t >= s.StartTick && t < s.StartTick + s.DurationTicks) ? PresentationDeterminism.Integer(shakes[0].Seed, t, -3, 3) : 0; return (object)new { id = "camera-state.camera.player-follow." + t, cameraId = "camera.player-follow", tick = t, targetEntityId = "player", authoritativeCenter = new { x, y = 90 }, presentationOffset = new { x = shake, y = 0 }, pixelSnappedCenter = new { x = x + shake, y = 90 }, clippedViewport = new { width = 320, height = 180 }, fingerprint = Fingerprint(new { t, x, shake, postLoad }) }; }).ToArray();
    private static object Prompt(bool postLoad, M021AuthoritativeSource? source) => postLoad ? new { promptId = "prompt.open-door", semanticActionId = "action.interact", targetEntityId = PersistentIds.Door, textResourceId = "text.prompt.open-door", enabled = source?.Snapshot.Doors.SingleOrDefault(x => x.EntityId == PersistentIds.Door)?.State == "open", reasonId = (string?)null, semanticInputActionId = "input.interact", priority = 10, runtimeTick = source?.Snapshot.RuntimeTick ?? 6, authoritativeSource = "authoritative-door-state", fingerprint = Fingerprint("prompt.open-door|" + (source?.Snapshot.RuntimeTick ?? 6)) } : new { promptId = "prompt.locked-door", semanticActionId = "action.interact", targetEntityId = PersistentIds.Door, textResourceId = "text.prompt.locked-door", enabled = false, reasonId = (string?)(source?.LockedDoorCondition.Detail ?? "condition-failed"), semanticInputActionId = "input.interact", priority = 10, runtimeTick = 3, authoritativeSource = "m020-condition-evaluation", fingerprint = Fingerprint("prompt.locked-door|" + (source?.LockedDoorCondition.Detail ?? "condition-failed")) };
    private static object? Notification(IReadOnlyList<EffectInstance> instances, IReadOnlyDictionary<string, EffectDefinition> definitions, bool postLoad) { if (postLoad) return null; var candidates = instances.Where(x => definitions[x.DefinitionId].NotificationTextId is not null).Select(x => new { requestId = "notification." + x.InstanceId, instanceId = "notification-instance." + x.InstanceId, textResourceId = definitions[x.DefinitionId].NotificationTextId, startTick = x.StartTick, durationTicks = 3, priority = x.DefinitionId == "effect.save-confirmation" ? 20 : 10, sourceEvent = x.SourceEventId, completed = x.CurrentAge >= 3 }).OrderByDescending(x => x.priority).ThenBy(x => x.startTick).ThenBy(x => x.instanceId, StringComparer.Ordinal).FirstOrDefault(); return candidates; }
    private static IEnumerable<object> BindingValues(PreparedPresentationState state) { var names = new[] { "player.health.current", "player.health.maximum", "player.health.normalized", "player.inventory.distinct-count", "player.inventory.item-count:item.collectible-crystal", "interaction.current.present", "interaction.current.enabled", "interaction.current.text-id", "interaction.current.reason-id", "notification.current.present", "notification.current.text-id", "save.last-status", "door:door.vault.state", "switch:switch.vault.state" }; return names.Select(x => new { bindingId = x, value = SemanticBindings.Resolve(x, state), source = "immutable-prepared-projection-state" }); }
    private static ParticleEmitterDefinition Emitter() => AuthoredEmitterCatalog.Load(Path.Combine(Root, "game", "effects", "effect.collection-burst.json"));
    private static UiElement Hud() => new("hud.root", "root", null, "top-left", 0, 0, 320, 180, 0, 0, 100, [new("hud.health", "progress-bar", "player.health.normalized", "top-left", 8, 8, 96, 10, 0, 0, 110, []), new("hud.inventory", "text", null, "top-left", 8, 24, 120, 8, 0, 0, 110, [], "text.notification.item-collected", "font.ui.default"), new("hud.prompt", "text", "interaction.current.present", "bottom-left", 8, 8, 200, 8, 0, 0, 120, [], "text.prompt.open-door", "font.ui.default"), new("hud.notification", "text", "notification.current.present", "top-right", 8, 8, 160, 8, 0, 0, 130, [], "text.notification.save-created", "font.ui.default")]);
    private static Dictionary<string, TextResource> Text() => new[] { new TextResource("text.prompt.collect-crystal", "Collect crystal", ["prompt"], "m021"), new TextResource("text.prompt.activate-switch", "Activate switch", ["prompt"], "m021"), new TextResource("text.prompt.open-door", "Open door", ["prompt"], "m021"), new TextResource("text.prompt.locked-door", "Locked — requires crystal and vault power", ["prompt"], "m021"), new TextResource("text.notification.item-collected", "Crystal collected", ["notification"], "m021"), new TextResource("text.notification.switch-activated", "Switch activated", ["notification"], "m021"), new TextResource("text.notification.door-opened", "Door opened", ["notification"], "m021"), new TextResource("text.notification.save-created", "Save created", ["notification"], "m021") }.ToDictionary(x => x.Id, StringComparer.Ordinal);
    private static Dictionary<string, FontResource> Fonts() => new[] { new FontResource("font.ui.default", "game/assets/raw/samples/ui-default.metrics.json", "fixed-8px-advance-v1", "ascii-required-v1", "m021") }.ToDictionary(x => x.Id, StringComparer.Ordinal);
    private static IReadOnlyList<object> Compose(IReadOnlyList<object> camera, IReadOnlyList<UiLayoutRecord> layout, IReadOnlyList<TextCommand> text, IReadOnlyList<ParticleSample> particles, string scenario, bool postLoad) => new object[] { new { order = 1, space = "world", kind = "authoritative-world", source = "immutable-runtime-snapshot" }, new { order = 2, space = "world", kind = "particles", count = particles.Count, source = "effect.collection-burst" }, new { order = 3, space = "world", kind = "camera-transform-and-clip", source = "camera.player-follow" }, new { order = 4, space = "screen", kind = "ui-layout", count = layout.Count, source = "ui.player-hud" }, new { order = 5, space = "screen", kind = "text-commands", count = text.Count, source = "font.ui.default" }, new { order = 6, space = "screen", kind = "final-frame", scenario, postLoad, fingerprint = Fingerprint(new { layout, text, particles, scenario, postLoad }) } };
    private static IReadOnlyList<PresentationEvent> Events() => [new("event.collection.0001", "item.collected", 1, "player", "crystal", "4,3", "post-commit"), new("event.damage.0001", "entity.damaged", 2, "hazard", "player", "5,3", "post-commit"), new("event.switch.0001", "switch.activated", 4, "player", "switch.vault", "8,3", "post-commit"), new("event.door.0001", "door.opened", 5, "player", "door.vault", "12,3", "post-commit"), new("operation.save.0001", "save.created", 6, null, null, "screen", "successful-persistence-operation")];
    private static Task Json(string directory, string name, object value) { Directory.CreateDirectory(directory); return File.WriteAllTextAsync(Path.Combine(directory, name), JsonSerializer.Serialize(value, CanonicalJson.Options)); }
    private static Task Lines<T>(string directory, string name, IEnumerable<T> values) { Directory.CreateDirectory(directory); return File.WriteAllLinesAsync(Path.Combine(directory, name), values.Select(x => JsonSerializer.Serialize(x))); }
    private static string Fingerprint(object value) => PresentationDeterminism.Hash(JsonSerializer.Serialize(value));
}
