using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Agentic2D.Engine;
using Agentic2D.Contracts;
using Agentic2D.ScenarioRunner;
using Agentic2D.Validation;
namespace Agentic2D.Rendering;

public sealed record RenderPoint(double X, double Y); public sealed record RenderSize(double Width, double Height); public sealed record RenderRect(RenderPoint Position, RenderSize Size); public sealed record RenderColor(byte R, byte G, byte B, byte A);
public sealed record RenderItem(string Id, string SourceKind, string SourceId, string VisualDefinitionId, string PartId, string AssetId, string RegionId, RenderRect Destination, string Anchor, string Layer, int Order, string SortMode, double YSort, string MapId, string SnapshotFingerprint, RenderColor Tint);
public sealed record RenderCommand(string Id, string Kind, string? ItemId, RenderItem? Item, string? Text = null);
public sealed record RenderFrame(string Schema, string SourceMode, string ScenarioId, string MapId, int Tick, string SnapshotFingerprint, string ProjectionFingerprint, IReadOnlyList<RenderItem> Items, IReadOnlyList<RenderCommand> Commands);
public sealed record RenderSnapshot(string Schema, string ScenarioId, string MapId, int Tick, string SnapshotFingerprint, IReadOnlyList<RenderSnapshotEntity> Entities);
public sealed record RenderSnapshotEntity(string Id, string DefinitionId, double X, double Y);
public sealed record RenderProjectionResult(RenderFrame Frame, RenderSnapshot Snapshot, IReadOnlyList<object> AssetBindings, IReadOnlyList<ContentValidationDiagnostic> Diagnostics);
public sealed class RenderProjectionService
{
    private readonly Dictionary<string, IReadOnlyList<RenderItem>> statics = new(StringComparer.Ordinal);
    public RenderProjectionResult ProjectScenario(string scenarioReference, string? mapReference = null, string sourceMode = "live")
    {
        var scenario = ScenarioSourceResolver.Resolve(scenarioReference); if (!scenario.IsSuccess) throw new InvalidOperationException("Scenario unavailable: " + scenarioReference); var load = ScenarioSourceLoader.Load(scenario.Source, scenario.Path); if (!load.IsSuccess) throw new InvalidOperationException("Scenario invalid");
        var mapId = mapReference ?? load.SourceScenario.Runtime?.MapId ?? MapContentValidator.InteractionSmokeMapId; var mapResolution = MapInspector.ResolveTarget(mapId); var mapItem = new MapContentValidator().ValidateFile(mapResolution.MapPath); if (mapItem.Map is null || mapItem.Status != ContentValidationStatus.Passed) throw new InvalidOperationException("Map invalid");
        var visuals = VisualDefinitionCatalog.LoadAll(out var visualDiagnostics); var defs = EntityDefinitionCatalog.LoadAll(out var definitionDiagnostics); var execution = M014ScenarioExecutor.Execute(load.SourceScenario); if (execution.World is null) throw new InvalidOperationException("Scenario execution did not create an inspectable runtime world.");
        var snapshot = execution.World.Snapshot(load.SourceScenario.Runtime!.Ticks); var entities = SnapshotEntities(snapshot, execution.Provenance ?? new Dictionary<string, RuntimeEntityProvenance>(StringComparer.Ordinal), defs); var renderSnapshot = new RenderSnapshot("agentic2d.render-snapshot.v1", load.SourceScenario.Id, mapItem.Map.Id, snapshot.Tick, snapshot.Fingerprint, entities);
        var staticItems = Static(mapItem.Map, visuals); var dynamicItems = Dynamic(renderSnapshot, visuals); var items = staticItems.Concat(dynamicItems).OrderBy(x => Layer(x.Layer)).ThenBy(x => x.Order).ThenBy(x => x.SortMode == "y" ? x.YSort : 0d).ThenBy(x => x.Id, StringComparer.Ordinal).ToArray();
        var commands = Compile(items); var fp = Fingerprint(items, commands); var frame = new RenderFrame("agentic2d.render-frame.v1", sourceMode, renderSnapshot.ScenarioId, renderSnapshot.MapId, renderSnapshot.Tick, renderSnapshot.SnapshotFingerprint, fp, items, commands); var assets = items.Select(x => x.AssetId).Distinct(StringComparer.Ordinal).Order().Select(id => Binding(id)).Cast<object>().ToArray(); return new(frame, renderSnapshot, assets, visualDiagnostics.Concat(definitionDiagnostics).ToArray());
    }
    public RenderProjectionResult ProjectPresentationSnapshot(ScenarioPresentationSnapshot source, string sourceMode = "live")
    {
        return ProjectSnapshot(new RenderSnapshot("agentic2d.render-snapshot.v1", source.ScenarioId, source.MapId, source.Tick, source.Fingerprint, source.Entities.Select(x => new RenderSnapshotEntity(x.Id, x.DefinitionId, x.X, x.Y)).ToArray()), sourceMode);
    }
    public RenderProjectionResult ProjectSnapshot(RenderSnapshot snapshot, string sourceMode = "snapshot")
    {
        var map = MapInspector.ResolveTarget(snapshot.MapId); var item = new MapContentValidator().ValidateFile(map.MapPath); if (item.Map is null) throw new InvalidOperationException("Snapshot map unavailable."); var visuals = VisualDefinitionCatalog.LoadAll(out var ds); var staticItems = Static(item.Map, visuals); var dynamicItems = Dynamic(snapshot, visuals); var items = staticItems.Concat(dynamicItems).OrderBy(x => Layer(x.Layer)).ThenBy(x => x.Order).ThenBy(x => x.SortMode == "y" ? x.YSort : 0d).ThenBy(x => x.Id, StringComparer.Ordinal).ToArray(); var commands = Compile(items); var fp = Fingerprint(items, commands); return new(new("agentic2d.render-frame.v1", sourceMode, snapshot.ScenarioId, snapshot.MapId, snapshot.Tick, snapshot.SnapshotFingerprint, fp, items, commands), snapshot, items.Select(x => x.AssetId).Distinct().Order().Select(id => Binding(id)).Cast<object>().ToArray(), ds);
    }
    /// <summary>Recompiles a read-only frame after presentation has derived animated render items.</summary>
    public RenderProjectionResult WithAnimatedItems(RenderProjectionResult source, IReadOnlyList<RenderItem> animatedItems)
    {
        var items = source.Frame.Items.Concat(animatedItems).OrderBy(x => Layer(x.Layer)).ThenBy(x => x.Order).ThenBy(x => x.SortMode == "y" ? x.YSort : 0d).ThenBy(x => x.Id, StringComparer.Ordinal).ToArray();
        var commands = Compile(items); var fingerprint = Fingerprint(items, commands);
        var frame = source.Frame with { Items = items, Commands = commands, ProjectionFingerprint = fingerprint };
        var bindings = items.Select(x => x.AssetId).Distinct(StringComparer.Ordinal).Order().Select(id => Binding(id)).Cast<object>().ToArray();
        return new RenderProjectionResult(frame, source.Snapshot, bindings, source.Diagnostics);
    }
    private IReadOnlyList<RenderItem> Static(MapContentSource map, VisualDefinitionCatalog visuals)
    { var key = map.Id + "|" + JsonSerializer.Serialize(map) + "|" + visuals.Revision + "|settings:320x180"; if (statics.TryGetValue(key, out var cached)) return cached; var results = new List<RenderItem>(); foreach (var cell in map.Layers.SelectMany(x => x.Cells.Select(c => (x, c))).OrderBy(x => x.c.Y).ThenBy(x => x.c.X)) { if (visuals.TryGet("visual-definition.ground.smoke", out var v)) results.AddRange(Parts("map-tile", $"{cell.x.Id}:{cell.c.X},{cell.c.Y}", v!, cell.c.X, cell.c.Y, map.Id, "static")); } foreach (var obj in map.Objects.OrderBy(x => x.Id)) { if (!string.IsNullOrWhiteSpace(obj.VisualDefinitionId) && visuals.TryGet(obj.VisualDefinitionId!, out var v)) results.AddRange(Parts("static-map-object", obj.Id, v!, obj.Position.X, obj.Position.Y, map.Id, "static")); } return statics[key] = results; }
    private static IReadOnlyList<RenderItem> Dynamic(RenderSnapshot s, VisualDefinitionCatalog visuals) { var r = new List<RenderItem>(); foreach (var e in s.Entities.OrderBy(x => x.Id, StringComparer.Ordinal)) if (visuals.TryGet(e.DefinitionId.Replace("entity-definition.", "visual-definition."), out var v)) r.AddRange(Parts("runtime-entity", e.Id, v!, e.X, e.Y, s.MapId, s.SnapshotFingerprint)); return r; }
    private static IEnumerable<RenderItem> Parts(string kind, string source, VisualDefinitionSource d, double x, double y, string map, string snap) => d.Parts.Select(p => new RenderItem($"render.{kind}.{source}.{p.Id}", kind, source, d.Id, p.Id, p.AssetId, p.RegionId, new(new(x + p.Offset.X, y + p.Offset.Y), new(p.WorldSize.Width, p.WorldSize.Height)), p.Anchor, p.Layer, p.Order, p.SortMode, y + p.Offset.Y, map, snap, new((byte)p.Tint.R, (byte)p.Tint.G, (byte)p.Tint.B, (byte)p.Tint.A)));
    private static IReadOnlyList<RenderSnapshotEntity> SnapshotEntities(EntityComponentSnapshot s, IReadOnlyDictionary<string, RuntimeEntityProvenance> p, EntityDefinitionCatalog d) { var values = s.Components.FirstOrDefault(x => x.TypeId == "component.continuous-transform-2d")?.Values ?? []; return values.Select(v => { using var j = JsonDocument.Parse(v.Value); return new RenderSnapshotEntity(v.EntityId, p.TryGetValue(v.EntityId, out var q) ? q.DefinitionId : "", j.RootElement.GetProperty("X").GetDouble(), j.RootElement.GetProperty("Y").GetDouble()); }).ToArray(); }
    private static IReadOnlyList<RenderCommand> Compile(IReadOnlyList<RenderItem> i) => [new("command.clear", "clear", null, null), new("command.world.begin", "begin-world-camera", null, null), .. i.Select(x => new RenderCommand("command.draw." + x.Id, "draw-texture-region", x.Id, x)), new("command.world.end", "end-world-camera", null, null), new("command.screen.begin", "begin-screen-space", null, null), new("command.screen.end", "end-screen-space", null, null)];
    private static object Binding(string id) => new { assetId = id, sourcePath = "game/assets/raw/samples/render-atlas-smoke.png", sourceFingerprint = "fixture", filtering = "point", fallback = false }; private static int Layer(string x) => Array.IndexOf(VisualDefinitionValidator.Layers, x); private static string Fingerprint(object a, object b) => "sha256:" + Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(a) + JsonSerializer.Serialize(b)))).ToLowerInvariant();
}
public static class RenderArtifactWriter { public static async Task WriteAsync(string output, RenderProjectionResult r) { Directory.CreateDirectory(output); var o = new JsonSerializerOptions { WriteIndented = true }; await File.WriteAllTextAsync(Path.Combine(output, "render-result.json"), JsonSerializer.Serialize(new { schema = "agentic2d.render-projection.result.v1", status = "passed", sourceMode = r.Frame.SourceMode, scenarioId = r.Frame.ScenarioId, mapId = r.Frame.MapId, tick = r.Frame.Tick, projectionFingerprint = r.Frame.ProjectionFingerprint }, o)); await File.WriteAllTextAsync(Path.Combine(output, "render-snapshot.json"), JsonSerializer.Serialize(r.Snapshot, o)); await File.WriteAllTextAsync(Path.Combine(output, "render-frame.json"), JsonSerializer.Serialize(r.Frame with { Items = [], Commands = [] }, o)); await File.WriteAllLinesAsync(Path.Combine(output, "render-items.jsonl"), r.Frame.Items.Select(x => JsonSerializer.Serialize(x))); await File.WriteAllLinesAsync(Path.Combine(output, "render-commands.jsonl"), r.Frame.Commands.Select(x => JsonSerializer.Serialize(x))); await File.WriteAllTextAsync(Path.Combine(output, "asset-bindings.json"), JsonSerializer.Serialize(r.AssetBindings, o)); await File.WriteAllTextAsync(Path.Combine(output, "render-diagnostics.json"), JsonSerializer.Serialize(new { schema = "agentic2d.render.diagnostics.v1", diagnostics = r.Diagnostics }, o)); } }
